# Generated by Django 4.2 on 2023-05-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_channel_name_alter_channel_publish_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='publish_interval',
            field=models.TextField(default=''),
        ),
    ]
