# Generated by Django 4.2 on 2023-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_channel_publish_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='themes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
