# Generated by Django 4.2.1 on 2023-05-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='theme',
            field=models.CharField(default='', max_length=200),
        ),
    ]
