# Generated by Django 4.2 on 2023-06-11 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='publish_interval',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
