# Generated by Django 4.2 on 2023-07-09 11:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_upload_channel_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='site_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='channel',
            name='vk_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='channel',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='overlay',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_overlay_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='template',
            field=models.TextField(blank=True, default='*Theme*', null=True),
        ),
    ]
