# Generated by Django 4.2 on 2023-07-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_channel_site_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='vk_api_key',
        ),
    ]
